CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  section TEXT NOT NULL,
  sub_topics TEXT[] NOT NULL,
  time_spent FLOAT NOT NULL,
  questions_done INTEGER DEFAULT 0,
  concept_mastered BOOLEAN DEFAULT FALSE,
  is_practice BOOLEAN DEFAULT FALSE,
  topic_questions JSONB
);

CREATE TABLE IF NOT EXISTS daily_tasks (
  id TEXT PRIMARY KEY,
  date DATE NOT NULL,
  task_name TEXT NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  UNIQUE(date, task_name)
);

CREATE TABLE IF NOT EXISTS resource_notes (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
